services:
  - type: web
    name: bookbazaar
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python bookbazaar/backend/manage.py collectstatic --noinput
    startCommand: |
      gunicorn bookbazaar.wsgi --workers 3 --chdir bookbazaar/backend --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "bookbazaar-0jew.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://bookbazaar-0jew.onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
